theme: jekyll-theme-minimal
title: Do geese see god
description: First attempt, just trying stuff
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: test
    url: test
